import { makeStyles, tokens, shorthands } from "@fluentui/react-components";

export const useNetworkingStyles = makeStyles({
  // ── Layout ────────────────────────────────────────
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    backgroundColor: "#fafbfc",
  },
  header: {
    flexShrink: 0,
    backgroundColor: "#fff",
    ...shorthands.borderBottom("1px", "solid", tokens.colorNeutralStroke2),
    ...shorthands.padding("20px", "32px", "0"),
  },
  headerTitle: {
    fontSize: "20px",
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
    letterSpacing: "-0.02em",
    marginBottom: "4px",
  },
  headerSubtitle: {
    fontSize: "13px",
    color: tokens.colorNeutralForeground3,
    marginBottom: "16px",
  },
  scrollArea: {
    flex: 1,
    overflowY: "auto",
    ...shorthands.padding("24px", "32px", "48px"),
  },
  content: {
    maxWidth: "960px",
  },

  // ── Security Posture Card ─────────────────────────
  postureCard: {
    backgroundColor: "#fff",
    ...shorthands.borderRadius("16px"),
    ...shorthands.padding("0"),
    marginBottom: "24px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
    ...shorthands.borderWidth("1px"),
    ...shorthands.borderStyle("solid"),
    ...shorthands.borderColor("rgba(0,0,0,0.06)"),
    overflow: "hidden",
  },
  postureHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    ...shorthands.padding("18px", "24px"),
    ...shorthands.borderBottom("1px", "solid", "rgba(0,0,0,0.05)"),
    backgroundColor: "#fafbfc",
  },
  postureTitle: {
    fontSize: "14px",
    fontWeight: 600,
    color: tokens.colorNeutralForeground1,
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  postureGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "0",
  },
  postureItem: {
    ...shorthands.padding("16px", "20px"),
    ...shorthands.borderRight("1px", "solid", "rgba(0,0,0,0.05)"),
    ...shorthands.borderBottom("1px", "solid", "rgba(0,0,0,0.05)"),
    cursor: "pointer",
    transitionProperty: "background-color",
    transitionDuration: "0.15s",
    "&:hover": {
      backgroundColor: "#f8f9fb",
    },
    "&:nth-child(3n)": {
      borderRightColor: "transparent",
    },
  },
  postureItemLabel: {
    fontSize: "11px",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    color: tokens.colorNeutralForeground3,
    marginBottom: "8px",
  },
  postureItemValue: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "13px",
    fontWeight: 500,
    color: tokens.colorNeutralForeground1,
  },
  postureStatusDot: {
    width: "8px",
    height: "8px",
    ...shorthands.borderRadius("50%"),
    flexShrink: 0,
  },

  // ── Topology / Flow Diagram ───────────────────────
  topologyCard: {
    backgroundColor: "#fff",
    ...shorthands.borderRadius("16px"),
    ...shorthands.padding("24px", "24px", "32px"),
    marginBottom: "24px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
    ...shorthands.borderWidth("1px"),
    ...shorthands.borderStyle("solid"),
    ...shorthands.borderColor("rgba(0,0,0,0.06)"),
    overflow: "visible",
  },
  topologyTitle: {
    fontSize: "11px",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    color: tokens.colorNeutralForeground3,
    marginBottom: "20px",
  },
  // Horizontal flow: all items use a shared "icon row" height so arrows align
  // with icon-box centers. Every direct child is a flex column that places
  // its icon at the same distance from the top of the row.
  topologyLayout: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0",
    ...shorthands.padding("8px", "0"),
    overflowX: "auto",
  },
  // Wraps the external source nodes (Internet, Front Door) + arrow + section box
  // into one group so their internal arrows align with the section's vertical center.
  topologyInboundGroup: {
    display: "flex",
    alignItems: "center",
    gap: "0",
  },
  // Section box — bordered container for inbound/outbound groups
  topologySection: {
    ...shorthands.borderRadius("12px"),
    ...shorthands.borderWidth("1.5px"),
    ...shorthands.borderStyle("dashed"),
    ...shorthands.borderColor("rgba(0,0,0,0.18)"),
    ...shorthands.padding("12px", "16px", "16px"),
    backgroundColor: "#f6f8fa",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    justifyContent: "center",
    alignSelf: "center",
  },
  topologySectionLabel: {
    fontSize: "10px",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    color: tokens.colorNeutralForeground3,
    textAlign: "center",
  },
  // Each path row inside a section (horizontal: nodes + arrows)
  topologyPathRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0",
  },
  // Separator between paths within a section
  topologyPathSeparator: {
    height: "1px",
    backgroundColor: "rgba(0,0,0,0.06)",
    ...shorthands.margin("0"),
  },
  // Center column: App node
  topologyCenter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    ...shorthands.padding("0", "4px"),
  },
  // Shared node styles — default uses normal flow for labels (inside section boxes).
  topologyNode: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "6px",
    minWidth: "70px",
    flexShrink: 0,
  },
  // Standalone node used in the main flow row (Internet, Front Door, App).
  // Labels are absolutely positioned below the icon box so the node's
  // flex height = just the icon, allowing arrows to center-align with icons.
  topologyNodeStandalone: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    minWidth: "70px",
    flexShrink: 0,
    position: "relative",
    marginBottom: "40px",
  },
  topologyNodeBox: {
    width: "44px",
    height: "44px",
    ...shorthands.borderRadius("12px"),
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "20px",
    fontWeight: 600,
    boxShadow: "0 2px 8px rgba(0,0,0,0.08)",
    transitionProperty: "transform, box-shadow",
    transitionDuration: "0.2s",
    cursor: "pointer",
    "&:hover": {
      transform: "translateY(-2px)",
      boxShadow: "0 6px 20px rgba(0,0,0,0.12)",
    },
  },
  // Larger node box for the central App
  topologyNodeBoxLarge: {
    width: "64px",
    height: "64px",
    ...shorthands.borderRadius("16px"),
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "16px",
    fontWeight: 700,
    boxShadow: "0 4px 16px rgba(0,0,0,0.12)",
    transitionProperty: "transform, box-shadow",
    transitionDuration: "0.2s",
    cursor: "pointer",
    "&:hover": {
      transform: "translateY(-2px)",
      boxShadow: "0 8px 24px rgba(0,0,0,0.16)",
    },
  },
  topologyNodeLabel: {
    fontSize: "11px",
    fontWeight: 600,
    color: tokens.colorNeutralForeground1,
    textAlign: "center",
    lineHeight: "14px",
  },
  topologyNodeSub: {
    fontSize: "10px",
    color: tokens.colorNeutralForeground3,
    textAlign: "center",
    maxWidth: "120px",
    lineHeight: "14px",
  },
  // Labels for standalone nodes — absolutely positioned below the icon box
  topologyNodeLabelAbs: {
    position: "absolute",
    top: "100%",
    marginTop: "6px",
    fontSize: "11px",
    fontWeight: 600,
    color: tokens.colorNeutralForeground1,
    textAlign: "center",
    lineHeight: "14px",
    whiteSpace: "nowrap",
  },
  topologyNodeSubAbs: {
    position: "absolute",
    top: "100%",
    marginTop: "22px",
    fontSize: "10px",
    color: tokens.colorNeutralForeground3,
    textAlign: "center",
    maxWidth: "140px",
    lineHeight: "14px",
    whiteSpace: "nowrap",
  },
  // Arrow connector between nodes.
  topologyArrow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    ...shorthands.padding("0", "8px"),
    flexShrink: 0,
    position: "relative",
  },
  // Arrow connecting sections (between section box and App)
  topologyArrowLong: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    ...shorthands.padding("0", "4px"),
    flexShrink: 0,
    position: "relative",
  },
  topologyArrowLine: {
    width: "28px",
    height: "2px",
    background: `linear-gradient(to right, ${tokens.colorNeutralStroke2}, ${tokens.colorBrandStroke1})`,
    position: "relative",
    "&::after": {
      content: '""',
      position: "absolute",
      right: "-1px",
      top: "-3px",
      width: "0",
      height: "0",
      borderTop: "4px solid transparent",
      borderBottom: "4px solid transparent",
      borderLeft: `5px solid ${tokens.colorBrandStroke1}`,
    },
  },
  topologyArrowLineLong: {
    width: "40px",
    height: "2px",
    background: `linear-gradient(to right, ${tokens.colorNeutralStroke2}, ${tokens.colorBrandStroke1})`,
    position: "relative",
    "&::after": {
      content: '""',
      position: "absolute",
      right: "-1px",
      top: "-3px",
      width: "0",
      height: "0",
      borderTop: "4px solid transparent",
      borderBottom: "4px solid transparent",
      borderLeft: `5px solid ${tokens.colorBrandStroke1}`,
    },
  },
  topologyArrowLabel: {
    position: "absolute",
    bottom: "calc(100% + 2px)",
    fontSize: "9px",
    color: tokens.colorNeutralForeground3,
    fontWeight: 500,
    whiteSpace: "nowrap",
  },

  // ── Section cards (shared for sub-panels) ─────────
  sectionCard: {
    backgroundColor: "#fff",
    ...shorthands.borderRadius("14px"),
    ...shorthands.padding("24px"),
    marginBottom: "16px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
    ...shorthands.borderWidth("1px"),
    ...shorthands.borderStyle("solid"),
    ...shorthands.borderColor("rgba(0,0,0,0.06)"),
  },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "20px",
  },
  sectionTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  sectionIcon: {
    width: "40px",
    height: "40px",
    ...shorthands.borderRadius("12px"),
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    fontSize: "20px",
  },
  sectionTitle: {
    fontSize: "16px",
    fontWeight: 600,
    color: tokens.colorNeutralForeground1,
    letterSpacing: "-0.01em",
  },
  sectionSubtitle: {
    fontSize: "13px",
    color: tokens.colorNeutralForeground3,
    marginTop: "2px",
  },
  sectionLabel: {
    fontSize: "11px",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    color: tokens.colorNeutralForeground3,
    marginBottom: "14px",
    display: "block",
  },

  // ── Property row / detail list ────────────────────
  propRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    ...shorthands.padding("12px", "16px"),
    ...shorthands.borderRadius("10px"),
    backgroundColor: "#f8f9fb",
    marginBottom: "8px",
  },
  propLabel: {
    fontSize: "13px",
    fontWeight: 500,
    color: tokens.colorNeutralForeground2,
    flexShrink: 0,
    minWidth: "100px",
  },
  propValue: {
    fontSize: "13px",
    fontWeight: 500,
    color: tokens.colorNeutralForeground1,
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "8px",
    fontFamily: "'SF Mono', 'Cascadia Code', 'Fira Code', monospace",
    minWidth: 0,
  },

  // ── Data table ────────────────────────────────────
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  tableHead: {
    fontSize: "11px",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    color: tokens.colorNeutralForeground3,
    ...shorthands.padding("10px", "14px"),
    textAlign: "left",
    ...shorthands.borderBottom("1px", "solid", "rgba(0,0,0,0.06)"),
  },
  tableCell: {
    ...shorthands.padding("12px", "14px"),
    fontSize: "13px",
    color: tokens.colorNeutralForeground1,
    ...shorthands.borderBottom("1px", "solid", "rgba(0,0,0,0.04)"),
    verticalAlign: "middle",
  },
  tableRow: {
    transitionProperty: "background-color",
    transitionDuration: "0.1s",
    "&:hover": {
      backgroundColor: "#f8f9fb",
    },
  },

  // ── Separator ─────────────────────────────────────
  separator: {
    height: "1px",
    background: "linear-gradient(to right, rgba(0,0,0,0.06), rgba(0,0,0,0.02))",
    ...shorthands.margin("20px", "0"),
  },

  // ── Toggle row ────────────────────────────────────
  toggleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    ...shorthands.padding("14px", "18px"),
    backgroundColor: "#f8f9fb",
    ...shorthands.borderRadius("10px"),
    marginBottom: "8px",
  },
  toggleLabel: {
    fontSize: "13px",
    fontWeight: 600,
    color: tokens.colorNeutralForeground1,
  },
  toggleDesc: {
    fontSize: "12px",
    color: tokens.colorNeutralForeground3,
    marginTop: "3px",
  },

  // ── Wizard cards ──────────────────────────────────
  wizardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "12px",
    marginBottom: "24px",
  },
  wizardCard: {
    ...shorthands.padding("20px"),
    backgroundColor: "#fff",
    ...shorthands.borderWidth("2px"),
    ...shorthands.borderStyle("solid"),
    ...shorthands.borderColor("rgba(0,0,0,0.06)"),
    ...shorthands.borderRadius("14px"),
    cursor: "pointer",
    transitionProperty: "all",
    transitionDuration: "0.2s",
    "&:hover": {
      ...shorthands.borderColor(tokens.colorBrandStroke1),
      boxShadow: "0 4px 16px rgba(102,126,234,0.12)",
      transform: "translateY(-2px)",
    },
  },
  wizardIcon: {
    width: "40px",
    height: "40px",
    ...shorthands.borderRadius("12px"),
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "12px",
    fontSize: "20px",
  },
  wizardTitle: {
    fontSize: "14px",
    fontWeight: 600,
    color: tokens.colorNeutralForeground1,
    marginBottom: "4px",
  },
  wizardDesc: {
    fontSize: "12px",
    color: tokens.colorNeutralForeground3,
    lineHeight: "18px",
  },

  // ── Warning / info bars ───────────────────────────
  warningBar: {
    display: "flex",
    alignItems: "flex-start",
    gap: "10px",
    ...shorthands.padding("14px", "18px"),
    backgroundColor: "#FFF8E1",
    ...shorthands.borderRadius("10px"),
    ...shorthands.borderWidth("1px"),
    ...shorthands.borderStyle("solid"),
    ...shorthands.borderColor("#FFE082"),
    marginBottom: "16px",
    fontSize: "13px",
    color: "#8D6E00",
    lineHeight: "20px",
  },
  infoBar: {
    display: "flex",
    alignItems: "flex-start",
    gap: "10px",
    ...shorthands.padding("14px", "18px"),
    backgroundColor: "#EEF2FF",
    ...shorthands.borderRadius("10px"),
    ...shorthands.borderWidth("1px"),
    ...shorthands.borderStyle("solid"),
    ...shorthands.borderColor("#C7D2FE"),
    marginBottom: "16px",
    fontSize: "13px",
    color: "#4338CA",
    lineHeight: "20px",
  },
  successBar: {
    display: "flex",
    alignItems: "flex-start",
    gap: "10px",
    ...shorthands.padding("14px", "18px"),
    backgroundColor: "#ECFDF5",
    ...shorthands.borderRadius("10px"),
    ...shorthands.borderWidth("1px"),
    ...shorthands.borderStyle("solid"),
    ...shorthands.borderColor("#A7F3D0"),
    marginBottom: "16px",
    fontSize: "13px",
    color: "#065F46",
    lineHeight: "20px",
  },

  // ── Empty state ───────────────────────────────────
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    ...shorthands.padding("40px", "20px"),
    textAlign: "center",
  },
  emptyIcon: {
    width: "56px",
    height: "56px",
    ...shorthands.borderRadius("16px"),
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "24px",
    marginBottom: "16px",
    backgroundColor: "#f1f3f5",
    color: tokens.colorNeutralForeground3,
  },
  emptyTitle: {
    fontSize: "15px",
    fontWeight: 600,
    color: tokens.colorNeutralForeground1,
    marginBottom: "6px",
  },
  emptyDesc: {
    fontSize: "13px",
    color: tokens.colorNeutralForeground3,
    lineHeight: "20px",
    maxWidth: "360px",
    marginBottom: "16px",
  },

  // ── Overview Properties ─────────────────────────
  addressesHeader: {
    marginBottom: "16px",
  },
  addressesGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "20px",
  },
  addressRow: {
    ...shorthands.padding("10px", "16px"),
    ...shorthands.borderRadius("10px"),
    backgroundColor: "#f8f9fb",
    marginBottom: "8px",
  },
  addressRowLabel: {
    display: "block",
    fontSize: "11px",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    color: tokens.colorNeutralForeground3,
    marginBottom: "8px",
  },
  showMoreButton: {
    fontSize: "12px",
    color: tokens.colorBrandForeground1,
    cursor: "pointer",
    fontWeight: 500,
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    backgroundColor: "transparent",
    ...shorthands.borderWidth("0"),
    ...shorthands.padding("2px", "0"),
    "&:hover": {
      textDecorationLine: "underline",
    },
  },
  ipList: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
    alignItems: "center",
  },
  toolbarContainer: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    marginBottom: "12px",
    marginLeft: "-8px",
  },

  // ── Command bar (save/discard) ─────────────────────
  commandBar: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    ...shorthands.padding("10px", "16px"),
    backgroundColor: "#EEF2FF",
    ...shorthands.borderRadius("10px"),
    ...shorthands.borderWidth("1px"),
    ...shorthands.borderStyle("solid"),
    ...shorthands.borderColor("#C7D2FE"),
    marginBottom: "16px",
  },
});
